version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    env_file:
      - .env

  frontend:
    build:
      context: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped